/** The 31 example names in Laravel's `FormFactory`. */
export const FORM_NAMES = [
  'Contact Form',
  'Inquiry / Quote Request Form',
  'Consultation Booking Form',
  'Newsletter Signup Form',
  'Callback Request Form',
  'Job Application Form',
  'Employee Onboarding Form',
  'Leave / Time-Off Request Form',
  'Performance Evaluation Form',
  'Expense Reimbursement Form',
  'Exit Interview Form',
  'Donation Form',
  'Checkout / Payment Form',
  'Grant Application Form',
  'Membership Renewal Form',
  'Refund / Return Request Form',
  'Event Registration Form',
  'Course Enrollment Form',
  'Student Admission Form',
  'RSVP Form',
  'Volunteer Sign-Up Form',
  'Customer Satisfaction Survey Form',
  'Product Feedback Form',
  'Bug Report Form',
  'Complaint / Grievance Form',
  'Market Research Questionnaire',
  'Consent / Release Form',
  'Non-Disclosure Agreement (NDA) Form',
  'Patient Intake / Health History Form',
  'Terms of Service Acceptance Form',
  'Liability Waiver Form',
] as const;
