/**
 * Port of Laravel's `Illuminate\Validation\Validator` for the rules this API
 * uses (ch. 4). One engine validates fixed endpoints (rule arrays in
 * `rules/*.rules.ts`) and form schemas, so both give identical error bodies.
 *
 * The evaluation model, rule expansion order, messages and `validated()`
 * output follow Laravel's source; `test/fixtures/validation/corpus.json`
 * (generated by PHP) pins the behaviour.
 */
import {
  dataGet,
  dataHas,
  escapeRegExp,
  gatherKeys,
  MISSING,
  PhpArrayBuilder,
  wildcardPattern,
} from './data';
import {
  replaceAttribute,
  summarize,
  template,
  type SizeType,
} from './messages';
import { strGetCsv, strSnake } from './php';
import {
  DEPENDENT_RULES,
  IMPLICIT_RULES,
  NUMERIC_RULES,
  RULES,
  SIZE_RULES,
  type RuleContext,
} from './rules';
import { parseDateTime } from './date';

/**
 * A rule that needs more than the input, such as a database lookup
 * (`exists`, `unique`, `current_password`) or a policy object (`password`).
 */
export interface RuleObject {
  /** Snake-case rule name: the message key and the name in `failedRules`. */
  readonly name: string;
  /** Runs even when the attribute is absent (like `required`). */
  readonly implicit?: boolean;
  /**
   * `true` passes. `false` fails with the `validation.{name}` template.
   * A list of templates fails with those messages (`:attribute` replaced).
   */
  check(
    value: unknown,
    attribute: string,
    context: ValidationContext,
  ): boolean | string[] | Promise<boolean | string[]>;
}

export type RuleSpec = string | RuleObject;
/** Rules per attribute; a string is split on `|`, as Laravel does. */
export type RuleSet = Record<string, RuleSpec[] | string>;

/** What custom rules and after hooks can see and do. */
export interface ValidationContext {
  readonly data: unknown;
  getValue(attribute: string): unknown;
  has(attribute: string): boolean;
  hasErrors(attribute?: string): boolean;
  addError(attribute: string, message: string): void;
}

export type AfterHook = (context: ValidationContext) => void | Promise<void>;

export interface ValidationResult {
  passes: boolean;
  /** Messages per attribute, in Laravel's order. */
  errors: Map<string, string[]>;
  /** First message plus "(and N more error[s])", or null when passing. */
  message: string | null;
  /** `validated()`: only attributes with rules, PHP-shaped. Null when failing. */
  validated: unknown;
}

export class UnsupportedRuleError extends Error {
  constructor(readonly rule: string) {
    super(`Unsupported validation rule: ${rule}`);
    this.name = 'UnsupportedRuleError';
  }
}

interface ParsedRule {
  /** Studly name, e.g. `DateFormat`. */
  name: string;
  params: string[];
  raw: RuleSpec;
  object?: RuleObject;
}

/** `Str::studly()`. */
function studly(value: string): string {
  return value
    .replace(/[-_]/g, ' ')
    .split(/\s+/u)
    .filter((word) => word !== '')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

/** `ValidationRuleParser::parse()`. */
function parseRule(rule: RuleSpec): ParsedRule {
  if (typeof rule !== 'string') {
    return { name: studly(rule.name), params: [], raw: rule, object: rule };
  }
  let name = rule;
  let params: string[] = [];
  const colon = rule.indexOf(':');
  if (colon >= 0) {
    name = rule.slice(0, colon);
    const parameter = rule.slice(colon + 1);
    params = ['regex', 'not_regex', 'notregex'].includes(name.toLowerCase())
      ? [parameter]
      : strGetCsv(parameter);
  }
  let studlyName = studly(name.trim());
  if (studlyName === 'Int') studlyName = 'Integer';
  if (studlyName === 'Bool') studlyName = 'Boolean';
  return { name: studlyName, params, raw: rule };
}

/**
 * Whether the engine can run a string rule: its name is looked up
 * case-insensitively, as PHP's method lookup is. Empty rules are skipped by
 * the engine, so they count as supported. Used by F7 (ch. 4 §4.5).
 */
export function isSupportedRule(rule: string): boolean {
  const { name } = parseRule(rule);
  return name === '' || RULES[name.toLowerCase()] !== undefined;
}

function explodeExplicit(rules: RuleSpec[] | string): RuleSpec[] {
  return typeof rules === 'string' ? rules.split('|') : rules;
}

export class Validator {
  private readonly rules = new Map<string, ParsedRule[]>();
  private readonly implicitAttributes = new Map<string, string[]>();
  private readonly messages = new Map<string, string[]>();
  private readonly failedRules = new Map<string, Map<string, string[]>>();

  constructor(
    ruleSet: RuleSet,
    private readonly data: unknown,
    private readonly after: AfterHook[] = [],
  ) {
    this.explode(ruleSet);
  }

  /** Validates and returns the outcome; never throws for invalid input. */
  async run(): Promise<ValidationResult> {
    this.messages.clear();
    this.failedRules.clear();

    for (const [attribute, rules] of this.rules) {
      for (const rule of rules) {
        await this.validateAttribute(attribute, rule);
        if (this.shouldStopValidating(attribute)) break;
      }
    }
    const context = this.context();
    for (const hook of this.after) await hook(context);

    const passes = this.messages.size === 0;
    return {
      passes,
      errors: new Map(this.messages),
      message: passes ? null : summarize([...this.messages.values()].flat()),
      validated: passes ? this.validated() : null,
    };
  }

  /**
   * `ValidationRuleParser::explodeRules()`: explicit attributes keep their
   * position; wildcard attributes are replaced by their concrete expansions,
   * appended in order (or merged into an attribute already listed).
   */
  private explode(ruleSet: RuleSet): void {
    const exploded = new Map<string, RuleSpec[] | null>();
    for (const key of Object.keys(ruleSet)) exploded.set(key, null);

    for (const [attribute, rules] of Object.entries(ruleSet)) {
      if (!attribute.includes('*')) {
        exploded.set(attribute, explodeExplicit(rules));
        continue;
      }
      const pattern = new RegExp(`^${wildcardPattern(attribute, '[^.]*')}$`);
      for (const key of gatherKeys(attribute, this.data)) {
        if (!key.startsWith(attribute) && !pattern.test(key)) continue;
        const expansions = this.implicitAttributes.get(attribute) ?? [];
        expansions.push(key);
        this.implicitAttributes.set(attribute, expansions);
        exploded.set(key, [
          ...(exploded.get(key) ?? []),
          ...explodeExplicit(rules),
        ]);
      }
      exploded.delete(attribute);
    }

    for (const [attribute, rules] of exploded) {
      this.rules.set(attribute, (rules ?? []).map(parseRule));
    }
  }

  private async validateAttribute(
    attribute: string,
    rule: ParsedRule,
  ): Promise<void> {
    if (rule.name === '') return;

    let params = rule.params;
    if (DEPENDENT_RULES.includes(rule.name)) {
      const keys = this.explicitKeys(attribute);
      if (keys.length > 0) {
        params = params.map((param) => {
          let index = 0;
          return param.replace(/\*/g, () => keys[index++] ?? '*');
        });
      }
    }

    const value = this.getValue(attribute);
    const validatable = this.isValidatable(rule, attribute, value);
    if (!validatable) return;

    if (rule.object) {
      await this.validateUsingRuleObject(
        attribute,
        value,
        rule.object,
        rule.name,
      );
      return;
    }

    const impl = RULES[rule.name.toLowerCase()];
    if (!impl) throw new UnsupportedRuleError(rule.name);
    if (!impl(this.ruleContext(attribute, value, params))) {
      this.addFailure(attribute, rule.name, params);
    }
  }

  private async validateUsingRuleObject(
    attribute: string,
    value: unknown,
    rule: RuleObject,
    studlyName: string,
  ): Promise<void> {
    const outcome = await rule.check(value, attribute, this.context());
    if (outcome === true) return;
    if (outcome === false) {
      this.addFailure(attribute, studlyName, []);
      return;
    }
    this.recordFailedRule(attribute, studlyName, []);
    for (const message of outcome) {
      this.addMessage(
        attribute,
        replaceAttribute(message, this.displayableAttribute(attribute)),
      );
    }
  }

  private ruleContext(
    attribute: string,
    value: unknown,
    params: string[],
  ): RuleContext {
    return {
      attribute,
      value,
      params,
      data: this.data,
      primaryAttribute: this.primaryAttribute(attribute),
      hasRule: (names) => this.hasRule(attribute, names),
      ruleParams: (name) => this.ruleParams(attribute, name),
      ruleParamsFor: (other, name) => this.ruleParams(other, name),
    };
  }

  private context(): ValidationContext {
    return {
      data: this.data,
      getValue: (attribute) => this.getValue(attribute),
      has: (attribute) => dataHas(this.data, attribute),
      hasErrors: (attribute) =>
        attribute === undefined
          ? this.messages.size > 0
          : this.messages.has(attribute),
      addError: (attribute, message) => this.addMessage(attribute, message),
    };
  }

  /** `Validator::isValidatable()`. */
  private isValidatable(
    rule: ParsedRule,
    attribute: string,
    value: unknown,
  ): boolean {
    return (
      this.presentOrRuleIsImplicit(rule, attribute, value) &&
      this.passesOptionalCheck(attribute) &&
      this.isNotNullIfMarkedAsNullable(rule, attribute) &&
      this.hasNotFailedPreviousRuleIfPresenceRule(rule, attribute)
    );
  }

  private isImplicit(rule: ParsedRule): boolean {
    return rule.object?.implicit === true || IMPLICIT_RULES.includes(rule.name);
  }

  /** Whitespace-only strings and absent attributes only run implicit rules. */
  private presentOrRuleIsImplicit(
    rule: ParsedRule,
    attribute: string,
    value: unknown,
  ): boolean {
    if (
      typeof value === 'string' &&
      value.replace(/^[ \t\n\r\0\v]+|[ \t\n\r\0\v]+$/g, '') === ''
    ) {
      return this.isImplicit(rule);
    }
    return dataHas(this.data, attribute) || this.isImplicit(rule);
  }

  /** `sometimes`: skip the attribute when its key is absent. */
  private passesOptionalCheck(attribute: string): boolean {
    return (
      !this.hasRule(attribute, ['Sometimes']) || dataHas(this.data, attribute)
    );
  }

  /** `nullable`: a null value skips every non-implicit rule. */
  private isNotNullIfMarkedAsNullable(
    rule: ParsedRule,
    attribute: string,
  ): boolean {
    if (this.isImplicit(rule) || !this.hasRule(attribute, ['Nullable']))
      return true;
    return dataGet(this.data, attribute) !== null;
  }

  private hasNotFailedPreviousRuleIfPresenceRule(
    rule: ParsedRule,
    attribute: string,
  ): boolean {
    return ['Unique', 'Exists'].includes(rule.name)
      ? !this.messages.has(attribute)
      : true;
  }

  /** `bail` stops at the first message; otherwise a failed implicit rule stops. */
  private shouldStopValidating(attribute: string): boolean {
    if (this.hasRule(attribute, ['Bail'])) return this.messages.has(attribute);
    const failed = this.failedRules.get(attribute);
    return (
      this.hasRule(attribute, IMPLICIT_RULES) &&
      failed !== undefined &&
      [...failed.keys()].some((name) => IMPLICIT_RULES.includes(name))
    );
  }

  private addFailure(attribute: string, rule: string, params: string[]): void {
    const message = this.makeReplacements(
      this.getMessage(attribute, rule),
      attribute,
      rule,
      params,
    );
    this.addMessage(attribute, message);
    this.recordFailedRule(attribute, rule, params);
  }

  private recordFailedRule(
    attribute: string,
    rule: string,
    params: string[],
  ): void {
    const failed =
      this.failedRules.get(attribute) ?? new Map<string, string[]>();
    failed.set(rule, params);
    this.failedRules.set(attribute, failed);
  }

  /** `MessageBag::add()`: identical messages for a key are kept once. */
  private addMessage(attribute: string, message: string): void {
    const list = this.messages.get(attribute) ?? [];
    if (!list.includes(message)) list.push(message);
    this.messages.set(attribute, list);
  }

  private getMessage(attribute: string, rule: string): string {
    const snake = strSnake(rule);
    return SIZE_RULES.includes(rule)
      ? template(snake, this.attributeType(attribute))
      : template(snake);
  }

  private attributeType(attribute: string): SizeType {
    if (this.hasRule(attribute, NUMERIC_RULES)) return 'numeric';
    if (this.hasRule(attribute, ['Array', 'List'])) return 'array';
    return 'string';
  }

  private makeReplacements(
    message: string,
    attribute: string,
    rule: string,
    params: string[],
  ): string {
    let out = replaceAttribute(message, this.displayableAttribute(attribute));
    switch (rule) {
      case 'Between':
        out = out
          .replaceAll(':min', params[0] ?? '')
          .replaceAll(':max', params[1] ?? '');
        break;
      case 'Min':
        out = out.replaceAll(':min', params[0] ?? '');
        break;
      case 'Max':
        out = out.replaceAll(':max', params[0] ?? '');
        break;
      case 'Size':
        out = out.replaceAll(':size', params[0] ?? '');
        break;
      case 'DateFormat':
        out = out.replaceAll(':format', params[0] ?? '');
        break;
      case 'AfterOrEqual': {
        const param = params[0] ?? '';
        out = out.replaceAll(
          ':date',
          parseDateTime(param) === null
            ? this.displayableAttribute(param)
            : param,
        );
        break;
      }
      case 'Different':
        out = out.replaceAll(
          ':other',
          this.displayableAttribute(params[0] ?? ''),
        );
        break;
    }
    return out;
  }

  /**
   * `getDisplayableAttribute()`: wildcard expansions are shown raw
   * (`schema.0.id`); other names are snake-cased with `_` → space.
   */
  private displayableAttribute(attribute: string): string {
    if (this.implicitAttributes.has(this.primaryAttribute(attribute)))
      return attribute;
    return strSnake(attribute).replaceAll('_', ' ');
  }

  private primaryAttribute(attribute: string): string {
    for (const [unparsed, parsed] of this.implicitAttributes) {
      if (parsed.includes(attribute)) return unparsed;
    }
    return attribute;
  }

  /** The concrete keys a wildcard attribute's `*` matched, for dependent rules. */
  private explicitKeys(attribute: string): string[] {
    const primary = this.primaryAttribute(attribute);
    const match = new RegExp(`^${wildcardPattern(primary, '([^.]*)')}`).exec(
      attribute,
    );
    return match ? match.slice(1) : [];
  }

  private hasRule(attribute: string, names: string[]): boolean {
    return (this.rules.get(attribute) ?? []).some((rule) =>
      names.includes(rule.name),
    );
  }

  private ruleParams(attribute: string, name: string): string[] | null {
    return (
      (this.rules.get(attribute) ?? []).find((rule) => rule.name === name)
        ?.params ?? null
    );
  }

  private getValue(attribute: string): unknown {
    const value = dataGet(this.data, attribute);
    return value === MISSING ? null : value;
  }

  /**
   * `Validator::validated()`: attributes with rules, set in rule order. An
   * `array`/`list` attribute with nested rules contributes only its nested
   * keys (`excludeUnvalidatedArrayKeys`).
   */
  private validated(): unknown {
    const out = new PhpArrayBuilder();
    const keys = [...this.rules.keys()];
    for (const [key, rules] of this.rules) {
      const value = dataGet(this.data, key);
      const hasNested = new RegExp(`^${escapeRegExp(key)}\\.+`);
      if (
        rules.some((rule) => rule.raw === 'array' || rule.raw === 'list') &&
        value !== null &&
        keys.some((other) => hasNested.test(other))
      ) {
        continue;
      }
      if (value !== MISSING) out.set(key, value);
    }
    return out.toJSON();
  }
}

/** Runs `rules` over `data`. */
export function validate(
  rules: RuleSet,
  data: unknown,
  after: AfterHook[] = [],
): Promise<ValidationResult> {
  return new Validator(rules, data, after).run();
}
